
name: 'build checkout action'
description: 'checkout'
inputs:
  git-version:
    description: 'git 版本'
    required: true

outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
