
name: 'setup nodejs action'
description: 'nodejs'
inputs:
  nvm-version:
    description: 'nvm 版本'
    required: true
  nodejs-version:
    description: 'nodejs 版本'
    required: true
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
