
name: 'build npm action'
description: 'npm'
inputs:
  npm-version:
    description: 'npm 版本'
    required: true
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node20'
  main: 'dist/index.js'
