
name: 'build npm action'
description: 'npm'
inputs:
  project-path:
    description: '项目路径'
    required: true
    default: './react-web'
  build-command:
    description: '构建命令'
    required: true
    default: 'build'  
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
