name: 'setup python action'
description: 'python'
inputs:
  virtual-env:
    description: '虚拟环境名称'
    required: false,
    default: 'virenv'   
  pip-version:
    description: 'pip 版本'
    required: false,
    default: '23.1.0'
  pkg-mode:
    description: '打包方式'
    required: false,
    default: 'setup'    
  work-dir:
    description: '工作目录'
    required: false,
    default: './demo-python312-pip'  
  require-file:
    description: '依赖文件路径'
    required: false,
    default: './requirements.txt'
outputs:
  virtual-env:
    description: '虚拟环境名称'
runs:
  using: 'node16'
  main: 'dist/index.js'
