
name: 'setup python action'
description: 'python'
inputs:
  virtual-env:
    description: '虚拟环境名称'
    required: false,
    default: 'virenv'   
  pip-version:
    description: 'pip 版本'
    required: false,
    default: '23.1.0'
outputs:
  virtual-env:
    description: '虚拟环境名称'
runs:
  using: 'node16'
  main: 'dist/index.js'
