
name: 'build gradle'
description: 'buildgradle'
inputs:
  work-dir:
    description: '工作目录'
    required: true
    default: './'
  build-cmd:
    description: '构建指令'
    required: true
    default: 'clean build'
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
