
name: 'build gradle'
description: 'buildgradle'
inputs:
  work-dir:
    description: '工作目录'
    required: true
    default: './'
  build-cmd:
    description: '构建指令'
    required: true
    default: 'clean build'
  skip-test:
    description: '跳过测试'
    required: true
    type: boolean
    default: false         
  other-params:
    description: '补充参数'
    required: false
    type: string
    default: '--debug --stacktrace'        
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
