
name: 'build  nuget'
description: 'nuget'
inputs:
  nuget-version:
    description: 'nuget 版本'
    required: true
    default: '6.13.2'
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
