
name: 'setup python action'
description: 'python'
inputs:
  conda-version:
    description: 'conda 版本'
    required: true
  python-version:
    description: 'python 版本'
    required: false
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node20'
  main: 'dist/index.js'
