
name: 'setup python action'
description: 'python'
inputs:
  conda-version:
    description: 'conda 版本'
    required: true,
    default: 'py39_25.3.1-1'
  python-version:
    description: 'python 版本'
    required: false,
    default: '3.9.18'
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node20'
  main: 'dist/index.js'
