
name: 'setup dotnet action'
description: 'dotnet'
inputs:
  dotnet-version:
    description: 'dotnet 版本'
    required: true
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
