
name: 'build gradle'
description: 'buildgradle'
inputs:
  work-dir:
    description: '工作目录'
    required: true
    default: './'
  out-file:
    description: '输出文件'
    required: true
    default: 'app'     
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
