
name: 'tool compress'
description: 'compress'
inputs:
  work-dir:
    description: '工作目录'
    required: true
    default: './'       
outputs:
  report:
    description: 'Generated output'
runs:
  using: 'node16'
  main: 'dist/index.js'
